# Generated by Django 2.2.14 on 2022-05-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20211102_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('Price_in', models.FloatField()),
                ('time_in', models.DateTimeField()),
                ('order_type', models.CharField(max_length=4)),
                ('bot', models.CharField(max_length=20)),
            ],
        ),
    ]
