# Generated by Django 2.2.14 on 2022-05-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='account_num',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='another_referral',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='ifsc',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='security',
        ),
        migrations.AddField(
            model_name='bot',
            name='bot_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_type',
            field=models.CharField(max_length=20),
        ),
    ]
