# Generated by Django 2.2.14 on 2022-05-18 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0011_auto_20220516_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot3',
            old_name='angel_API_keys',
            new_name='binance_API_keys',
        ),
        migrations.RenameField(
            model_name='bot3',
            old_name='password',
            new_name='binance_Secret_Keys',
        ),
        migrations.RenameField(
            model_name='bot4',
            old_name='angel_API_keys',
            new_name='binance_API_keys',
        ),
        migrations.RenameField(
            model_name='bot4',
            old_name='password',
            new_name='binance_Secret_Keys',
        ),
        migrations.RemoveField(
            model_name='bot3',
            name='username',
        ),
        migrations.RemoveField(
            model_name='bot4',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='angel_API_keys',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='angel_password',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='angel_username',
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_st', models.DateTimeField(auto_now=True)),
                ('otp', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
