# Generated by Django 2.2.14 on 2022-05-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_user1_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='orders',
            name='bot',
            field=models.IntegerField(),
        ),
    ]
