# Generated by Django 2.2.14 on 2022-05-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20220523_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='Max_drawdown',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bot',
            name='Total_invested',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bot',
            name='Total_trades',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bot',
            name='Total_transaction',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bot',
            name='profits',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='bot',
            name='symbols_used',
            field=models.CharField(default="{'BTCUSDT': 1, 'BNBUSDT': 1, 'SOLUSDT': 1, 'BNBUSDT': 1}", max_length=80),
        ),
        migrations.AddField(
            model_name='bot',
            name='winning',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user1',
            name='Max_drawdown',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user1',
            name='Total_invested',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user1',
            name='Total_transaction',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user1',
            name='bots_owned',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='user1',
            name='profits',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user1',
            name='symbols_used',
            field=models.CharField(default="{'BTCUSDT': 1, 'BNBUSDT': 1, 'SOLUSDT': 1, 'BNBUSDT': 1}", max_length=80),
        ),
        migrations.AddField(
            model_name='user1',
            name='winning',
            field=models.IntegerField(default=100),
        ),
    ]
