# Generated by Django 2.2.14 on 2022-07-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20220523_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='tradingview_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('Price_in', models.FloatField()),
                ('time_in', models.FloatField()),
                ('order_type', models.CharField(max_length=20)),
                ('transaction_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='user1',
            name='bots_owned',
        ),
        migrations.AddField(
            model_name='user1',
            name='passphrase',
            field=models.CharField(default='danAFDqwcGlrbaQvAAMo', max_length=50),
        ),
        migrations.AlterField(
            model_name='user1',
            name='symbols_used',
            field=models.CharField(default="{'BTCUSDT': 100, 'BNBUSDT': 0, 'SOLUSDT': 0, 'BNBUSDT': 0}", max_length=80),
        ),
    ]
