# Generated by Django 2.2.14 on 2022-07-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20220703_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='kucoin_api_keys',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='user1',
            name='kucoin_password',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='user1',
            name='kucoin_secret_keys',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='user1',
            name='passphrase',
            field=models.CharField(default='StcohKFXzFGviNvxnJyP', max_length=50),
        ),
    ]
