# Generated by Django 2.2.14 on 2022-07-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20220704_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashboard_analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('Price_in', models.FloatField()),
                ('time_in', models.FloatField()),
                ('order_type', models.CharField(max_length=20)),
                ('transaction_type', models.CharField(max_length=20)),
                ('broker', models.CharField(default='NONE', max_length=20)),
                ('quantity', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='tradingview_orders',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user1',
            name='passphrase',
            field=models.CharField(default='JMvWLkPmFSoeDQatTZlc', max_length=50),
        ),
    ]
