# Generated by Django 2.2.14 on 2022-07-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20220706_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='passphrase',
            field=models.CharField(default='ctinYMdMwKeXIsqRhveM', max_length=50),
        ),
    ]
