# Generated by Django 2.2.14 on 2022-07-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20220706_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='passphrase',
            field=models.CharField(default='eEHswQvaGQxStfYrbMou', max_length=50),
        ),
    ]
