# Generated by Django 2.2.14 on 2022-07-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20220706_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='passphrase',
            field=models.CharField(default='TFblUExzbaweOvyATofE', max_length=50),
        ),
    ]
