# Generated by Django 2.2.14 on 2022-07-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20220706_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='angel_api_keys',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='user1',
            name='angel_client_id',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
        migrations.AddField(
            model_name='user1',
            name='angel_password',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
        migrations.AlterField(
            model_name='user1',
            name='passphrase',
            field=models.CharField(default='jVaLjxyMyUKGcLaBiXfg', max_length=50),
        ),
    ]
