# Generated by Django 2.2.14 on 2022-07-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20220716_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='telegram_chat_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user1',
            name='passphrase',
            field=models.CharField(default='cKniGHFAFibDMpqVwqTo', max_length=50),
        ),
    ]
