# Generated by Django 4.0.6 on 2022-08-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_bot_id_alter_bot1_id_alter_bot2_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='passphrase',
            field=models.CharField(default='EdOKBINNTdLntvSvTTUw', max_length=50),
        ),
    ]
