# Generated by Django 4.0.6 on 2022-08-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_user1_passphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='passphrase',
            field=models.CharField(default='tyybWrvVnwcctaoBuKkM', max_length=50),
        ),
    ]
