# Generated by Django 4.0.6 on 2022-07-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.CharField(default='NONE', max_length=20)),
                ('condition_type', models.CharField(default='INDICATOR', max_length=20)),
                ('indicator', models.CharField(default='NONE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.CharField(default='NONE', max_length=20)),
                ('strategy_name', models.CharField(default='NONE', max_length=50)),
                ('interval', models.CharField(default='1D', max_length=20)),
                ('crypto', models.CharField(default='BTCUSDT', max_length=20)),
                ('candle_type', models.CharField(default='ohlc', max_length=20)),
                ('pyramiding', models.IntegerField(default=1)),
            ],
        ),
    ]
